"""Defines the AgentState TypedDict for LangGraph."""
from typing import TypedDict, List, Optional


class AgentState(TypedDict):
    """
    State object that flows through the LangGraph workflow.
    
    Attributes:
        user_query: The original user's vague idea/request.
        style_description: Detailed visual/aesthetic description generated by Style Optimizer.
        construction_plan: Text plan generated by Agent A (Planner).
        selected_item_ids: List of item IDs selected by Agent B (Inventory Clerk).
        flux_prompt: Optimized prompt for FLUX API generated by Agent C.
        final_image_url: URL of the generated image from FLUX.
        retry_count: Number of retry attempts (feedback loops) between Planner and Clerk.
        clerk_feedback: Optional feedback message from Agent B explaining missing parts.
        status: Current status of the workflow ("processing", "success", "failed_no_parts").
        is_clerk_successful: Whether Agent B successfully found matching inventory items.
    """
    user_query: str
    style_description: str
    construction_plan: Optional[str]
    selected_item_ids: List[str]
    flux_prompt: Optional[str]
    final_image_url: Optional[str]
    retry_count: int
    clerk_feedback: Optional[str]
    status: str
    is_clerk_successful: bool

