"""Defines the AgentState TypedDict for LangGraph."""
from typing import TypedDict, List, Optional


class AgentState(TypedDict):
    """
    State object that flows through the LangGraph workflow.
    
    Attributes:
        user_query: The original user's vague idea/request.
        construction_plan: Text plan generated by Agent A (Planner).
        selected_item_ids: List of item IDs selected by Agent B (Inventory Clerk).
        flux_prompt: Optimized prompt for FLUX API generated by Agent C.
        final_image_url: URL of the generated image from FLUX.
    """
    user_query: str
    construction_plan: Optional[str]
    selected_item_ids: List[str]
    flux_prompt: Optional[str]
    final_image_url: Optional[str]

