"""Defines the AgentState TypedDict for LangGraph."""
from typing import TypedDict, List, Optional, Dict, Any


class AgentState(TypedDict):
    """
    State object that flows through the LangGraph workflow.
    
    Attributes:
        user_query: The original user's vague idea/request.
        conversation_history: List of conversation messages (user and agent).
        conversation_data: Dictionary of gathered information from conversation.
        skip_conversation: Whether user wants to skip the conversation.
        ready_for_workflow: Whether enough information has been gathered to proceed.
        style_description: Detailed visual/aesthetic description generated by Style Optimizer.
        construction_plan: Text plan generated by Agent A (Planner).
        selected_item_ids: List of item IDs selected by Agent B (Inventory Clerk).
        flux_prompt: Optimized prompt for FLUX API generated by Agent C.
        final_image_url: URL of the generated image from FLUX.
        assembly_manual_prompts: List of prompts for each assembly step.
        assembly_manual_images: List of image URLs for each assembly step.
        retry_count: Number of retry attempts (feedback loops) between Planner and Clerk.
        clerk_feedback: Optional feedback message from Agent B explaining missing parts.
        status: Current status of the workflow ("processing", "success", "failed_no_parts", "conversation").
        is_clerk_successful: Whether Agent B successfully found matching inventory items.
    """
    user_query: str
    conversation_history: List[Dict[str, Any]]
    conversation_data: Dict[str, Any]
    skip_conversation: bool
    ready_for_workflow: bool
    style_description: str
    construction_plan: Optional[str]
    selected_item_ids: List[str]
    flux_prompt: Optional[str]
    final_image_url: Optional[str]
    assembly_manual_prompts: List[Any]
    assembly_manual_images: List[str]
    retry_count: int
    clerk_feedback: Optional[str]
    status: str
    is_clerk_successful: bool

